### ISSUE TITLE
Add a CONTRIBUTING.md file or instructions for contributors?

### ISSUE THREAD

**Issue by kinow** [tobias-dv-lnu/s4rdm3x#11]
Hi

From https://github.com/openjournals/joss-reviews/issues/2791

Just wondering if there are any plans to document how others can contribute to `s4rdm3x`? Related to the following topic in the review process

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Or maybe there's something already in the docs that I've missed?

Thanks!

**Comment by tobias-dv-lnu** [comment]
There is a small section at the end of the docs: https://tobias-dv-lnu.github.io/s4rdm3x/

The main way of continuing development is to write new mappers: the main steps to do so is documented in: https://tobias-dv-lnu.github.io/s4rdm3x/add_new_mapper

Maybe this should be made clearer in some way...

**Comment by kinow** [comment]
Sorry, I missed that part @tobias-dv-lnu . I think a simple short paragraph or link to the section on how to contribute/write a custom mapper could be useful, or what do you expect from the contribution (e.g. include tests? add javadocs to important methods/code added, etc?).

But good enough for the paper review :+1: plus I consider the vast amount of tests and the example experiment provided good ways to help users how to contribute too (i.e. by example). Feel free to close it if you'd like :+1:

**Comment by tobias-dv-lnu** [comment]
Good point! I will add a docs issue for this!
