### ISSUE TITLE
s4rdm3x_1.2.zip missing from GH release?

### ISSUE THREAD

**Issue by kinow** [tobias-dv-lnu/s4rdm3x#6]
Hi @tobias-dv-lnu ,

I'm following the installation instructions, and it looks like the latest release on GH is missing a ZIP that's present in the other two? I'm downloading a src file, but not sure if it will have the jars I need to keep following the docs?

Related to <https://github.com/openjournals/joss-reviews/issues/2791>

Thanks
Bruno

**Comment by tobias-dv-lnu** [comment]
Yes, release 1.2 was a source-only release, basically adding the gradle stuff. Zip with jars from 1.1 should be fine. I will add the 1.1 release zip to release 1.2 to make it consistent with the documentation.

Sorry for the confusion.

/T

**Comment by kinow** [comment]
> Yes, release 1.2 was a source-only release, basically adding the gradle stuff. Zip with jars from 1.1 should be fine. I will add the 1.1 release zip to release 1.2 to make it consistent with the documentation.
> 
> Sorry for the confusion.
> 
> /T

Not a problem. Just wanted to confirm before trying to run the code. Thanks🙂

**Comment by tobias-dv-lnu** [comment]
Great! Closing this issue now :)

/T
